version: "3.7"
services:
    preproc:
        image: afam00/peds-brain-tumor-preproc:1.0.0
        hostname: 'preproc'
        volumes:
            - ./input:/input
            - ./preprocessed:/preprocessed
    skull-strip:
        image: afam00/peds-brain-auto-skull-strip:0.0.0
        hostname: 'peds-brain-auto-skull-strip'
        volumes:
            - ./preprocessed:/input
            - ./preprocessed:/output
        depends_on:
            preproc:
                condition: service_completed_successfully
    tumor-segmentation:
        image: afam00/peds-brain-auto-seg:1.2.0
        hostname: 'peds-brain-auto-seg'
        volumes:
            - ./preprocessed:/input
            - ./output:/output
        depends_on:
            preproc:
                condition: service_completed_successfully
    normalization:
        image: afam00/peds-brain-intensity-normalization:0.0.0
        hostname: 'peds-brain-intensity-normalization'
        volumes:
            - ./preprocessed:/input
            - ./output:/output
        depends_on:
            skull-strip:
                condition: service_completed_successfully
    feature-extraction:
        image: afam00/peds-brain-feat-extract:0.0.0
        hostname: 'peds-brain-feat-extract'
        volumes:
            - ./output:/input
            - ./output:/output
        depends_on:
            normalization:
                condition: service_completed_successfully
            tumor-segmentation:
                condition: service_completed_successfully